server:
  port: 8085

spring:
  application:
    name: rich
  mvc:
    view:
      prefix: "/WEB-INF/views/"
      suffix: ".jsp"
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521/XE
    username: dongs2
    password: 1234
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
mybatis:
  mapper-locations: classpath:mapper/*.xml # 매퍼 파일 경로
  type-aliases-package: com.kcc.rich.domain, com.kcc.rich.dto # 타입 별칭 패키지 (필요 시)
