spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521/XE
    username: kt
    password: 1234
mybatis:
  mapper-locations: classpath:mapper/*.xml # 매퍼 파일 경로
  type-aliases-package: com.kcc.rich.domain # 타입 별칭 패키지 (필요 시)