server:
  port: 8085
spring:
  application:
    name: rich
  mvc:
    view:
      prefix: "/WEB-INF/views/"
      suffix: ".jsp"
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521/XE
    username: kcc
    password: 1234
  cache:
    jcache:
      config: classpath:ehcache.xml
mybatis:
  mapper-locations: classpath:mapper/*.xml # 매퍼 파일 경로
  type-aliases-package: com.kcc.rich.domain, com.kcc.rich.dto # 타입 별칭 패키지 (필요 시)

payment:
  toss:
    test_client_api_key : test_ck_Z61JOxRQVEzBdO1dYJ9DrW0X9bAq
    test_secret_api_key : test_gsk_docs_OaPz8L5KdmQXkzRz3y47BMw6
    success_url : "http://localhost:8085/payments/toss/success"
    fail_url : "http://localhost:8085/payments/toss/fail"